### PR TITLE
Add a plugin system for customizing Qubes VMs

### PR DESCRIPTION
**Pull request by qubesuser**
These commits add the ability for users to define "plugins" that alter the way Qubes VMs work, to allow to prototype and create custom functionality without having to change the Qubes code.

This is done by adding a few new "hooks_" hooks, and having a new module that add hooks allowing to run Python scripts or executables from plugins in the filesystem.

Since it uses the existing hooks mechanism and most of the code is contained in a new module, the patches are minimally invasive.

Example use cases:
- Alter the libvirt XML on every start in a way that still incorporates changes using the normal GUI and doesn't require to start the VM in a special way
- Create or manipulate private.img before every boot
- Call qrexec services after the VM is started
- Start daemons that interact with the VM

Needs marmarek/qubes-manager#3
# Status of the code

Currently some hooks can only be provided as Python hooks, because they transform non-string data and that's not supported yet.

Ordering of plugins is done by shelling to the "tsort" program and should instead use a topological sort implemented in Python. There is also no handling for the case of cyclical dependencies and it's not clear what to do (fail? ignore?).

It doesn't touch backup, maybe some changes are needed to properly backup plugins and plugin instances.
# Plugins

Plugins are defined /etc/qubes/plugins or /usr/share/qubes/plugins and consist of a "hooks" subdirectory where hooks can be defined with the name of the internal hooks with "_" replaced with "-".

Plugins can also have "before" and "after" files that determine the order in which plugins are executed.

Ordering can also be specified in a "plugins.order" that may be created in the same directory of a plugins dir.
# Hooks

Hooks can be:
- A directory, which causes hook execution to recurse it
- Have a ".py" extension, which causes them to be loaded as Python modules and a global function called "hook" to be called with globals set
- Executable, which causes them to be executed as subprocesses with environment variables set

Some hooks are classified as "transform hooks" that transform something, such as the config XML.

Python transform hooks have the data is passed in the first argument, and returned from the function. Executable transform hooks have it passed to stdin and expect the output on stdout.
# Plugin instances

Plugin instances must have the same name as a plugin and instruct Qubes to execute that plugin, with the configuration provided in the plugin instance.

Plugin instances can be configured:
- Per-VM, by putting them in /var/lib/qubes/appvms/<vm>/plugins
- For each VM with a template, by putting them in /var/lib/qubes/vm-templates/<vm>/appvm-plugins
- For each VM with a name matching a regex, by putting them in /etc/qubes/regex-plugins/<regex>

A plugin instance can either be a configuration file, or a directory in which case if the plugin requires a configuration file it should be called "conf".

There can be only a single instance per plugin, so plugins should be written to take multiple instances from configuration if that would be useful.

### CODE REVIEW

**Comment by marmarek** [comment]
Lack of such flexibility is exactly the reason why we've decided to
rewrite core code more python-way. The new core (aka "core3") currently
is sill quite unusable (we're currently working on qvm-start...), but
the code is much easier to extend. Especially adding such plugins is
much easier there.
Since we're working hard on core3, which also include porting all the
features implemented in the meantime in core2, I'm not going to merge
this to the current core code.

Current core3 code is here:
https://github.com/woju/qubes-core-admin/tree/core3-devel
WARNING: this tree is subject to frequent rebase.

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by qubesuser** [comment]
The idea is to allow extensibility by just dropping shell scripts that run at certain points of startup or that modify certain data (like the config XML) without needing to write Python code interfacing with the core, and in a modular way, and if that's considered a good thing it seems that something like this code would be needed regardless of how the Python code is refactored.

The core3-devel branch seems to still use, at least at the moment, the same core-modules and hooks_ mechanism, so this code should still be mergeable there (the commit adding additional hooks may perhaps need adjustments).

**Comment by marmarek** [comment]
On Fri, Oct 02, 2015 at 06:59:10AM -0700, qubesuser wrote:

> The core3-devel branch seems to still use, at least at the moment, the same core-modules and hooks_ mechanism, so this code should still be mergeable there (the commit adding additional hooks may perhaps need adjustments).

No, you should look at "qubes" directory. "core" and "core-modules" are
only the source from where we're rewriting the code.

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by qubesuser** [comment]
It looks like the hooks have been removed, so there would need to be a patch adding them back or introducing some other way to invoke the plugins.

BTW, looking at the core3 code, it seems you are still keeping the PV v HVM, AppVM vs NetVM and normal DispVM as separate Python classes, but this doesn't seem a good design since one might want an HVM NetVM (maybe for a modem that only has Windows drivers), a disposable HVM (for Windows) or even a disposable HVM NetVM and so on.

**Comment by marmarek** [comment]
On Fri, Oct 02, 2015 at 07:10:38AM -0700, qubesuser wrote:

> It looks like the hooks have been removed, so there would need to be a patch adding them back or introducing some other way to invoke the plugins.

There is events API for that. Details in documentation (linked from readme).

> BTW, looking at the core3 code, it seems you are still keeping the PV v HVM, AppVM vs NetVM and normal DispVM as separate Python classes, but this doesn't seem a good design since one might want an HVM NetVM (maybe for a modem that only has Windows drivers), a disposable HVM (for Windows) or even a disposable HVM NetVM and so on.

Yes, PV and HVM will be merged. Actually HVM class wasn't migrated yet -
will be integrated into main QubesVM.

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
As stated above - new core (will) have events API. Documentation here:
https://ftp.qubes-os.org/~woju/core3doc/qubes-events.html

Extensions (https://ftp.qubes-os.org/~woju/core3doc/qubes-ext.html) can provide own event handlers, and can be registered using entry points python API (this part isn't documented yet...). This means it is really easy to write new extension, or even extension for calling shell scripts to handle any event.
Because of this, closing this pull request.

**Pull request closed without merging**
